# Generated by Django 5.0.6 on 2024-07-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_todo_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-created_at']},
        ),
    ]
